//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaudaMaster.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerStoreRelation
    {
        public int CustomerStoreID { get; set; }
        public int CustomerID { get; set; }
        public int StoreID { get; set; }
        public string Description { get; set; }
        public bool RewardCheck { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Store Store { get; set; }
    }
}
