//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaudaMaster.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListHeader()
        {
            this.ListDetails = new HashSet<ListDetail>();
        }
    
        public int ListHeaderID { get; set; }
        public int CustomerID { get; set; }
        public string ListName { get; set; }
        public string ListCreationDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListDetail> ListDetails { get; set; }
    }
}
