//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaudaMaster.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Categories = new HashSet<Category>();
            this.CustomerStoreRelations = new HashSet<CustomerStoreRelation>();
            this.Items = new HashSet<Item>();
            this.ListStoreAssociations = new HashSet<ListStoreAssociation>();
        }
    
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public string StoreAddressPrimary { get; set; }
        public string StoreAddressSecondary { get; set; }
        public string StoreContact { get; set; }
        public string StoreContactPerson { get; set; }
        public string StoreEstablishmentDate { get; set; }
        public string StoreDescription { get; set; }
        public string StoreUsername { get; set; }
        public string StorePassword { get; set; }
        public string StoreTitle { get; set; }
        public string StoreLogo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerStoreRelation> CustomerStoreRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListStoreAssociation> ListStoreAssociations { get; set; }
    }
}
